-- Migration: 004_enhance_clause_table.sql
-- Description: Add AI extraction fields to clause table
-- Author: Phase 2 - Database Integration
-- Date: 2026-01-11

-- ==============================================================================
-- UP Migration
-- ==============================================================================

-- Add new fields for AI-extracted clause data
ALTER TABLE clause ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE clause ADD COLUMN IF NOT EXISTS beneficiary_party VARCHAR(255);
ALTER TABLE clause ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(4,3);

-- Add check constraint for confidence score (0.0 to 1.0)
ALTER TABLE clause ADD CONSTRAINT clause_confidence_score_check
  CHECK (confidence_score IS NULL OR (confidence_score >= 0.0 AND confidence_score <= 1.0));

-- Add index for querying by confidence score (low confidence clauses need review)
CREATE INDEX idx_clause_confidence_score ON clause(confidence_score) WHERE confidence_score IS NOT NULL;

-- Add index for filtering by beneficiary party
CREATE INDEX idx_clause_beneficiary_party ON clause(beneficiary_party) WHERE beneficiary_party IS NOT NULL;

-- Add comments
COMMENT ON COLUMN clause.summary IS
'Brief 1-2 sentence summary of the clause, generated by Claude AI.
Provides quick understanding without reading full raw_text.
Example: "Requires 95% annual availability, calculated excluding Force Majeure events."';

COMMENT ON COLUMN clause.beneficiary_party IS
'Party that benefits from this clause (Seller/Buyer/Both/Other).
Extracted by Claude AI from contract text. May be NULL if not applicable.
Example: "Buyer" for availability guarantees, "Seller" for payment terms.';

COMMENT ON COLUMN clause.confidence_score IS
'AI extraction confidence score from 0.0 (low) to 1.0 (high).
Indicates Claude AI''s confidence in the accuracy of extracted data.
Clauses with score < 0.7 may require human review.';

-- Helper function: Get clauses requiring review (low confidence)
CREATE OR REPLACE FUNCTION get_clauses_needing_review(
  p_confidence_threshold NUMERIC DEFAULT 0.7,
  p_limit INTEGER DEFAULT 100
) RETURNS TABLE (
  contract_id BIGINT,
  clause_id BIGINT,
  clause_name VARCHAR,
  confidence_score NUMERIC,
  summary TEXT,
  raw_text VARCHAR
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.contract_id,
    c.id AS clause_id,
    c.name AS clause_name,
    c.confidence_score,
    c.summary,
    c.raw_text
  FROM clause c
  WHERE c.confidence_score IS NOT NULL
    AND c.confidence_score < p_confidence_threshold
  ORDER BY c.confidence_score ASC, c.created_at DESC
  LIMIT p_limit;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION get_clauses_needing_review IS
'Returns clauses with low AI confidence scores that may need human review.
Default threshold is 0.7 (70% confidence). Returns up to 100 results by default.';

-- Helper function: Get clause statistics for a contract
CREATE OR REPLACE FUNCTION get_contract_clause_stats(
  p_contract_id BIGINT
) RETURNS TABLE (
  total_clauses BIGINT,
  avg_confidence NUMERIC,
  low_confidence_count BIGINT,
  clauses_by_type JSONB,
  clauses_by_category JSONB
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*)::BIGINT AS total_clauses,
    AVG(confidence_score) AS avg_confidence,
    COUNT(*) FILTER (WHERE confidence_score < 0.7)::BIGINT AS low_confidence_count,
    jsonb_object_agg(
      ct.code,
      type_counts.count
    ) FILTER (WHERE ct.code IS NOT NULL) AS clauses_by_type,
    jsonb_object_agg(
      cc.code,
      category_counts.count
    ) FILTER (WHERE cc.code IS NOT NULL) AS clauses_by_category
  FROM clause c
  LEFT JOIN clause_type ct ON c.clause_type_id = ct.id
  LEFT JOIN clause_category cc ON c.clause_category_id = cc.id
  LEFT JOIN LATERAL (
    SELECT COUNT(*)::INTEGER AS count
    FROM clause
    WHERE contract_id = p_contract_id
      AND clause_type_id = c.clause_type_id
  ) type_counts ON TRUE
  LEFT JOIN LATERAL (
    SELECT COUNT(*)::INTEGER AS count
    FROM clause
    WHERE contract_id = p_contract_id
      AND clause_category_id = c.clause_category_id
  ) category_counts ON TRUE
  WHERE c.contract_id = p_contract_id
  GROUP BY p_contract_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION get_contract_clause_stats IS
'Returns statistical summary of clauses for a contract including:
- Total clause count
- Average confidence score
- Number of low-confidence clauses
- Distribution by clause type
- Distribution by clause category';

-- Update existing clauses with default values
-- NOTE: This is safe to run on existing data
UPDATE clause
SET
  confidence_score = 0.5,  -- Default medium confidence for existing clauses
  summary = 'Legacy clause - summary not available'
WHERE summary IS NULL
  AND created_at < NOW() - INTERVAL '1 day';  -- Only update old records

