#!/usr/bin/env python3
"""
Generate Mermaid Entity Relationship Diagram from PostgreSQL database.
Connects to Supabase and extracts table structures and relationships.
"""

import os
import psycopg2
from typing import List, Dict

def get_tables(cursor) -> List[str]:
    """Get all tables in public schema."""
    cursor.execute("""
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
        ORDER BY table_name;
    """)
    return [row[0] for row in cursor.fetchall()]

def get_columns(cursor, table_name: str) -> List[Dict]:
    """Get columns for a table."""
    cursor.execute("""
        SELECT
            column_name,
            data_type,
            is_nullable,
            column_default
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = %s
        ORDER BY ordinal_position;
    """, (table_name,))

    return [{
        'name': row[0],
        'type': row[1],
        'nullable': row[2] == 'YES',
        'default': row[3]
    } for row in cursor.fetchall()]

def get_foreign_keys(cursor) -> List[Dict]:
    """Get all foreign key relationships."""
    cursor.execute("""
        SELECT
            tc.table_name AS from_table,
            kcu.column_name AS from_column,
            ccu.table_name AS to_table,
            ccu.column_name AS to_column
        FROM information_schema.table_constraints AS tc
        JOIN information_schema.key_column_usage AS kcu
            ON tc.constraint_name = kcu.constraint_name
            AND tc.table_schema = kcu.table_schema
        JOIN information_schema.constraint_column_usage AS ccu
            ON ccu.constraint_name = tc.constraint_name
            AND ccu.table_schema = tc.table_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
        AND tc.table_schema = 'public';
    """)

    return [{
        'from_table': row[0],
        'from_column': row[1],
        'to_table': row[2],
        'to_column': row[3]
    } for row in cursor.fetchall()]

def generate_mermaid(tables: List[str], columns_map: Dict, foreign_keys: List[Dict]) -> str:
    """Generate Mermaid ERD syntax."""

    mermaid = ["```mermaid", "erDiagram"]

    # Define entities
    for table in tables:
        columns = columns_map.get(table, [])

        # Add table definition
        mermaid.append(f"    {table.upper()} {{")

        for col in columns[:8]:  # Limit to first 8 columns for readability
            type_str = col['type'].replace(' ', '_')
            pk_marker = " PK" if col['name'] == 'id' else ""
            mermaid.append(f"        {col['type']} {col['name']}{pk_marker}")

        if len(columns) > 8:
            mermaid.append(f"        string ... ({len(columns) - 8} more columns)")

        mermaid.append("    }")

    # Add relationships
    mermaid.append("")
    for fk in foreign_keys:
        # Determine relationship cardinality (simplified)
        cardinality = "||--o{"  # One-to-many (most common)

        from_table = fk['from_table'].upper()
        to_table = fk['to_table'].upper()
        label = fk['from_column']

        mermaid.append(f"    {to_table} {cardinality} {from_table} : {label}")

    mermaid.append("```")

    return "\n".join(mermaid)

def main():
    # Connect to database
    db_url = os.environ.get('DATABASE_URL') or os.environ.get('SUPABASE_DB_URL')

    if not db_url:
        print("Error: DATABASE_URL or SUPABASE_DB_URL environment variable not set")
        exit(1)

    try:
        conn = psycopg2.connect(db_url)
        cursor = conn.cursor()

        print("📊 Generating Mermaid ERD from database...")

        # Extract schema information
        tables = get_tables(cursor)
        print(f"Found {len(tables)} tables")

        columns_map = {}
        for table in tables:
            columns_map[table] = get_columns(cursor, table)

        foreign_keys = get_foreign_keys(cursor)
        print(f"Found {len(foreign_keys)} foreign key relationships")

        # Generate Mermaid diagram
        mermaid_content = generate_mermaid(tables, columns_map, foreign_keys)

        # Write to file
        output_file = "database/diagrams/schema.mermaid.md"
        os.makedirs(os.path.dirname(output_file), exist_ok=True)

        with open(output_file, 'w') as f:
            f.write(f"# Database Schema - Entity Relationship Diagram\n\n")
            f.write(f"**Auto-generated from database**\n\n")
            f.write(f"This diagram is automatically generated by GitHub Actions when schema changes are pushed.\n\n")
            f.write(mermaid_content)

        print(f"✅ Mermaid diagram written to {output_file}")
        print(f"\n💡 View diagram:")
        print(f"   - GitHub: Navigate to database/diagrams/schema.mermaid.md")
        print(f"   - VS Code: Open file and press Cmd+Shift+V")
        print(f"   - Mermaid Live: Copy content to https://mermaid.live")

        cursor.close()
        conn.close()

    except psycopg2.Error as e:
        print(f"Database error: {e}")
        exit(1)
    except Exception as e:
        print(f"Error: {e}")
        exit(1)

if __name__ == "__main__":
    main()
